### ISSUE TITLE
Add "Contributing" Page

### ISSUE THREAD

**Issue by M2613** [capsule-corp-ternoa/ternoa-doc#68]
Create a page to explain how to contribute on the doc and follow best practices.

Here an example : [https://wiki.polkadot.network/docs/contributing](https://wiki.polkadot.network/docs/contributing)

**Comment by Balianos** [comment]
### Saved MEMO from JIRA, do not delete please : 

## Think about a Contributor Program to create a Documentation : 

Find a reward system for contributions via a github feature to be able to define metrics (if possible number of commits, lines of code, PR returns...).

First thing to do : technical feasibility study



## Get TOP 3 issues from Ternoa Developers

Ask on discord for a Top3 typical issue encountered by developers

Push developpers on stackoverflow/reddit to write about Ternoa cases



### Relevant Metrics ideas

PRs merged : last week, quarter, whole time

PRs reviewed : most comments / PR and/or applied LGTM (Looks Good To Me)

Types of Issues

Unrelevant tests - How to detect issue is assigned to the team ?

Opened

Assigned to teams/people

Fixed

Time to fix

Issues fixed - fixed mean that their PRs have been merged.

Opened

Assigned to teams/people

Fixed

Time to fix

Bugs - how to detect that issue is a bug? Labelling with Bug

Opened

Assigned to teams/people

Fixed

Time to fix

help-wanted issues fixed - how to detect such issue ? By label help-wanted ?

Histograms (all time, last week, last month)

PRs assigned to someone for review

Issues assigned

PRs commented

PRs created (could be broken down by Ternoa Dev vs Anon Dev maybe ?)

Top commenters

Number of companies contributing - With Comment

Latency

Time PR is opened to “LGTM”

Time LGTM to approve / merge

Time before any comments or activities from someone other than the author

review latency histogram, perhaps broken down by various attributes, such as size, api-change or not, by SIG, etc.

Number of PRs blocked on:

Number of PRs waiting for tests to be triggered - Identify with Label

Release Note - Identify with Label

LGTM

Approval

Number of PRs from Non-Ternoa Contributors vs Ternoa Contributors

Number of PRs from non-org contributors (histogram).  Easy to see when someone should be promoted into the org - How to distinguish them…?

For the people who rebase, how often do they need to be rebased

Rebases per PR : how often are PRs rebased in general - Detect with Label ?

How many rebases are necessary - How to detect it ? Count label needs-rebase in given date period?

How many times the repo is starred

How often does the bot remove LGTM

Commits per week across all repos

Team mentions

How often the team is notified - With Regex on the comments with @ ?

How often PRs are reassigned

How often an approver other than the suggested one approves

How long PRs are stuck for all the various reasons

Latency from PR creation to first LGTM state

Latency from first LGTM to final merge

Which proportion of time the submit queue is blocked

How long builds & tests take to run

How frequently are the various bot commands used - Detect Bot assistancy improvement

Differences in productivity stats between the Ternoa repo and other Targetted repos we should be compared, aligned



## Identify Top Priority Metrics : 

Number of team mentions

Number of reviewers (time unrestricted, monthly window histogram for example)- Defined as people who have added LGTM / Approve label- Or have written /lgtm or /approve command in a comment ?

Number of approvers over time

Time to go LGTM / Approve state on an issue - the amount of time from PR opening until approval label is applied or LGTM state confirmed

Number of PRs Merged per Repo



## Monitoring Plugins :

- https://github.com/lowlighter/metrics
- https://github.com/benbalter/open_source_stats
- https://github.com/marketplace/actions/github-organization-member-contribution-report-action
- https://github.com/soda480/github-contributions
